---
- hosts: blog
  user: root
  tasks:
    - name: clean exist blog files
      shell: rm -r /home/geosmart.top/*
    - name: copy new blog files
      src: /mnt/hgfs/WorkSpace/NoteSpace/geosmart.github.io/hexo/public
      dest: /home/geosmart.top
  handlers:
    - name: restart nginx
      service: name=nginx  state=restarted
